const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const E=require('../site/piano-engine.js');
function setup({mic=false}={}){
 const nodes=[];class Element{constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.textContent='';this._value='';nodes.push(this);}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}setAttribute(k,v){this.attrs[k]=v;}get value(){return this._value||this.children.find(n=>n.tag==='option')?.value||'';}set value(v){this._value=v;}get options(){return this.children;}addEventListener(){}click(){return this.onclick?.();}}
 const root=new Element('section'),tempo=new Element('input'),metronome=new Element('button');tempo.value='60';metronome.textContent='Start metronome';let frame,signal=null,stopped=0;
 const input={id:'keyboard',name:'Test keyboard',state:'connected'},access={inputs:new Map([['keyboard',input]])};const storage=new Map();
 class AudioContext{constructor(){this.sampleRate=48000;this.currentTime=0;}resume(){return Promise.resolve();}close(){return Promise.resolve();}createMediaStreamSource(){return {connect(){},disconnect(){}};}createAnalyser(){return {getFloatTimeDomainData(samples){for(let i=0;i<samples.length;i++)samples[i]=signal===null?0:.2*Math.sin(2*Math.PI*440*2**((signal-69)/12)*i/48000);}};}}
 const context={window:{PianoEngine:E,addEventListener(){}},document:{createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),querySelector:s=>s==='#note-trainer'?root:s==='#tempo'?tempo:s==='#metronome'?metronome:null,addEventListener(){}},navigator:{requestMIDIAccess:async()=>access,mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){stopped++;}}]})}},AudioContext,Float32Array,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},requestAnimationFrame:cb=>(frame=cb,1),cancelAnimationFrame:()=>{frame=null;},setTimeout,clearTimeout,console};
 vm.runInNewContext(fs.readFileSync('site/piano-player.js','utf8'),context);
 const button=text=>nodes.find(n=>n.tag==='button'&&n.textContent===text),feedback=()=>nodes.find(n=>n.className==='trainer-feedback').textContent;
 return {button,feedback,storage,input,nodes,setSignal:n=>{signal=n;},tick:t=>{const cb=frame;frame=null;cb?.(t);},get stopped(){return stopped;}};
}
const ode=[64,64,65,67,67,65,64,62,60,60,62,64,64,62,62];
test('MIDI adapter completes only through input and saves excerpt pass',async()=>{const ui=setup();await ui.button('Connect MIDI').onclick();for(const n of ode){ui.input.onmidimessage({data:[144,n,100]});if(ui.input.onmidimessage)ui.input.onmidimessage({data:[128,n,0]});}assert.match(ui.feedback(),/Passed this excerpt! 100%/);assert.equal(ui.input.onmidimessage,null);assert.match(ui.storage.get('journey-note-passes-v1'),/MIDI/);});
test('wrong MIDI attacks prevent a low-accuracy attempt passing',async()=>{const ui=setup();await ui.button('Connect MIDI').onclick();for(let i=0;i<4;i++){ui.input.onmidimessage({data:[144,50,100]});ui.input.onmidimessage({data:[128,50,0]});}for(const n of ode){ui.input.onmidimessage({data:[144,n,100]});if(ui.input.onmidimessage)ui.input.onmidimessage({data:[128,n,0]});}assert.match(ui.feedback(),/79% pitch accuracy/);assert.equal(ui.storage.size,0);});
test('microphone adapter requires stable notes and releases stream after passing',async()=>{const ui=setup();await ui.button('Listen with microphone').onclick();let t=100;for(const n of ode){ui.setSignal(n);for(let i=0;i<3;i++){ui.tick(t);t+=60;}ui.setSignal(null);for(let i=0;i<2;i++){ui.tick(t);t+=60;}}assert.match(ui.feedback(),/Passed this excerpt! 100%/);assert.equal(ui.stopped,1);assert.match(ui.storage.get('journey-note-passes-v1'),/microphone/);});
test('stopping pending microphone permission releases late stream',async()=>{const ui=setup();const pending=ui.button('Listen with microphone').onclick();ui.button('Stop input').onclick();await pending;assert.equal(ui.stopped,1);assert.match(ui.feedback(),/Input stopped/);});
